#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Checking styling, tests and building before commit'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Make the changes required above.'
    false;
)

# Testing
npm run check-test ||
(
    echo 'Make sure test are ok and coverage is between the threshold'
    false;
)

echo 'Trying to build now.'

npm run build ||
(
    echo 'Next build failed: View the errors above to see why.'
    false;
)

echo 'Everything looks fine, committing'
